name: Pull Request
description: Open a pull request to the Transloco repo

body:
  - type: checkboxes
    attributes:
      label: "Please check if your PR fulfills the following requirements:"
      options:
        - render: markdown
          label: "The commit message follows our guidelines: https://github.com/ngneat/transloco/blob/master/CONTRIBUTING.md#commit"
          required: true
          
        - label: Tests for the changes have been added (for bug fixes / features)
          required: true
          
        - label: Docs have been added / updated (for bug fixes / features)
          required: true
          
  - type: dropdown
    attributes:
      label: What kind of change does this PR introduce?
      options:
        - Bugfix
        - Feature
        - Code style update (formatting, local variables)
        - Refactoring (no functional changes, no api changes)
        - Build related changes
        - CI related changes
        - Documentation content changes
        - Other
    validations:
      required: true

  - type: textarea
    attributes:
      label: Please describe the changes.
      description: Fill this if you choose "Other" in the previus section.
      
  - type: textarea
      attributes:
        label: What is the current behavior?
        description: Please describe the current behavior that you are modifying, or link to a relevant issue.
        placeholder: "Issue Number: "
      validations:
        required: true
          
  - type: textarea
      attributes:
        label: What is the new behavior?
        
  - type: dropdown
    attributes:
      label: Does this PR introduce a breaking change?
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: Breaking changes.
      description: If this PR contains a breaking change, please describe the impact and migration path for existing applications.
      
  - type: textarea
    attributes:
      label: Other information
